/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Personaje.Personaje;
import java.awt.Image;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Sergio
 */
public class VentanaZonaDescanso extends javax.swing.JFrame {

    private ArrayList<Personaje> equipo;
    private Partida partida;
    private int numClic;

    /**
     * Creates new form JFrameZonaDescanso
     * @param equipo el equipo del usuario
     * @param partida los datos de la partida
     */
    public VentanaZonaDescanso(ArrayList<Personaje> equipo, Partida partida) {

        initComponents();

        this.equipo = equipo;
        this.partida = partida;
        numClic = 0;

        ImageIcon image = new ImageIcon("../TierraDesolada/imagenes/eventos/hoguera.png");
        Icon icono = new ImageIcon(image.getImage().getScaledInstance(jLabelHoguera.getWidth(), jLabelHoguera.getHeight(), Image.SCALE_DEFAULT));
        jLabelHoguera.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHoguera = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHoguera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHogueraMouseClicked(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoguera, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelHoguera, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHogueraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHogueraMouseClicked
        //Recupera la vida y mana a los personajes del equipo con 1 clic y al segundo clic te lleva a partida
        if (numClic == 0) {
            for (int i = 0; i < equipo.size(); i++) {//regeneramos el mana tras la pelea
                equipo.get(i).setSalud(equipo.get(i).getVidaMaxima());
                equipo.get(i).setMana(equipo.get(i).getManaMaximo());
            }
            jTextField1.setText("Todos los componentes del equipo recuperaron su salud y su maná");
            numClic++;
        } else {
            
            this.setVisible(false);
            partida.getMapa().setEventosRealizados(partida.getMapa().getEventosRealizados() + 1);
            try {
                partida.actualizar();

            } catch (IOException ex) {
                Logger.getLogger(VentanaCofre.class.getName()).log(Level.SEVERE, null, ex);
            }

            partida.setVisible(true);
        }
    }//GEN-LAST:event_jLabelHogueraMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelHoguera;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
